### ISSUE TITLE
ADOPTA: Rutas del backend

### ISSUE THREAD

**Issue by ArnauBadenas** [PaulaGDopico/SantuarioAnimal#10]

**Comment by ArnauBadenas** [comment]
# Rutas hechas
- Create 1 animal
- Get all animales
- Delete 1 animal (id)
- Update 1 animal (id)

Se necesitan mas? @PaulaGDopico @jose2995

**Comment by PaulaGDopico** [comment]
La info de un solo animal.
PD: Esto avisa una mierda hasta ahora lo miro.
